### ISSUE TITLE
Create project from PasteScript template does not work when rdc.etl is installed from egg

### ISSUE THREAD

**Issue by hartym** [rdcli/rdc.etl#5]
Missing files in egg.

> Traceback (most recent call last):
>   File "/Users/rd/Sites/MyPrj/.py-env/bin/paster", line 9, in <module>
>     load_entry_point('PasteScript==1.7.5', 'console_scripts', 'paster')()
>   File "/Users/rd/Sites/MyPrj/.py-env/lib/python2.7/site-packages/paste/script/command.py", line 104, in run
>     invoke(command, command_name, options, args[1:])
>   File "/Users/rd/Sites/MyPrj/.py-env/lib/python2.7/site-packages/paste/script/command.py", line 143, in invoke
>     exit_code = runner.run(args)
>   File "/Users/rd/Sites/MyPrj/.py-env/lib/python2.7/site-packages/paste/script/command.py", line 238, in run
>     result = self.command()
>   File "/Users/rd/Sites/MyPrj/.py-env/lib/python2.7/site-packages/paste/script/create_distro.py", line 137, in command
>     template, output_dir, vars)
>   File "/Users/rd/Sites/MyPrj/.py-env/lib/python2.7/site-packages/paste/script/create_distro.py", line 196, in create_template
>     template.run(self, output_dir, vars)
>   File "/Users/rd/Sites/MyPrj/.py-env/lib/python2.7/site-packages/paste/script/templates.py", line 58, in run
>     self.write_files(command, output_dir, vars)
>   File "/Users/rd/Sites/MyPrj/.py-env/lib/python2.7/site-packages/paste/script/templates.py", line 127, in write_files
>     template_renderer=self.template_renderer)
>   File "/Users/rd/Sites/MyPrj/.py-env/lib/python2.7/site-packages/paste/script/copydir.py", line 71, in copy_dir
>     names = os.listdir(source)
> OSError: [Errno 2] No such file or directory: '/Users/rd/Sites/MyPrj/.py-env/lib/python2.7/site-packages/rdc/etl/extra/tools/templates/project'

**Comment by hartym** [comment]
Deprecated. Use [Bonobo ETL](https://www.bonobo-project.org/).
